name: Generate

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: false
      - name: Download and extract Zig
        run: |
          curl -L -o zig.tar.xz https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
          tar -xJf zig.tar.xz
          mv zig-linux-x86_64-0.14.0 zig
          echo "$GITHUB_WORKSPACE/zig" >> $GITHUB_PATH

      - name: Download and build bzip2 0.9.0c (from 1998)
        run: |
          curl -L -o bzip2.tar.gz https://github.com/libarchive/bzip2/archive/refs/tags/bzip2-0.9.0c.tar.gz
          tar -xzf bzip2.tar.gz
          mv bzip2-bzip2-0.9.0c bzip2-0.9.0c
          sed -i 's|ar clq|zig ar clq|' bzip2-0.9.0c/Makefile
          cd bzip2-0.9.0c
          make CC=gcc
          mkdir -p $GITHUB_WORKSPACE/bin
          cp bzip2 $GITHUB_WORKSPACE/bin/bzip2-0.9.0c
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          $GITHUB_WORKSPACE/bin/bzip2-0.9.0c --version

      - name: Install gzip
        run: |
            sudo apt-get install -y gzip bzip2
            gzip --version
            bzip2 --version

      - name: Compress files in data folder
        run: |
          mkdir -p compressed
          rm -f compressed/*
          for file in data/*; do
            for level in 1 2 3 4 5 6 7 8 9; do
              bzip2 -k -$level "$file" -c > "compressed/$(basename "$file").bzip2-$level.bz2"
              bzip2-0.9.0c -k -$level "$file" -c > "compressed/$(basename "$file").bzip2-0.9.0-$level.bz2"
              gzip -k -$level "$file" -c > "compressed/$(basename "$file").gzip-$level.gz"
              gzip -k -$level -f "$file" -c > "compressed/$(basename "$file").gzip-filtered-$level.gz"
              gzip -k -$level -h "$file" -c > "compressed/$(basename "$file").gzip-huffman-$level.gz"
              gzip -k -$level -r "$file" -c > "compressed/$(basename "$file").gzip-rle-$level.gz"
            done
          done

      - name: Create gzip artifact zip
        run: |
          zip -r gzip-files.zip compressed/*.gz

      - name: Create bzip2 artifact zip
        run: |
          zip -r bzip2-files.zip compressed/*.bz2

      - name: Upload gzip artifact
        uses: actions/upload-artifact@v4
        with:
          name: gzip-files
          path: gzip-files.zip

      - name: Upload bzip2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: bzip2-files
          path: bzip2-files.zip
